[package]
name = "terminal_chat"
version = "0.1.0"
authors = ["Nilstrieb <nils.heydecker@gmx.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
